services:
  romeo-bot:
    build: .
    container_name: romeo-bot
    restart: unless-stopped
    volumes:
      - ./sounds:/app/sounds
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
